import React from 'react';

const TextBody = (htmlToRender, textWidth) => {
  return (
    <div className="text-container">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Congue mauris rhoncus aenean vel elit. Fusce id velit ut tortor pretium viverra. Neque volutpat ac tincidunt vitae semper quis. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Id diam vel quam elementum pulvinar etiam non quam lacus. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Nisl vel pretium lectus quam id leo. Eget est lorem ipsum dolor sit amet. Quam elementum pulvinar etiam non quam lacus. A lacus vestibulum sed arcu non. Ac turpis egestas sed tempus urna et. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Pretium quam vulputate dignissim suspendisse. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo.

  Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Ipsum dolor sit amet consectetur adipiscing elit ut. Volutpat diam ut venenatis tellus in metus vulputate. Et odio pellentesque diam volutpat commodo sed egestas egestas. Risus feugiat in ante metus dictum. Eget aliquet nibh praesent tristique magna sit amet. Aliquam ut porttitor leo a diam sollicitudin tempor id eu. Semper risus in hendrerit gravida rutrum. Commodo ullamcorper a lacus vestibulum sed arcu non. Pharetra diam sit amet nisl. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Faucibus purus in massa tempor nec. Neque sodales ut etiam sit amet. Et magnis dis parturient montes nascetur ridiculus. A lacus vestibulum sed arcu non odio euismod lacinia. Mi eget mauris pharetra et ultrices neque ornare aenean euismod. Sed vulputate mi sit amet mauris commodo quis. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla.

  Lacinia at quis risus sed vulputate. Justo nec ultrices dui sapien eget. Aliquam id diam maecenas ultricies. Consectetur lorem donec massa sapien faucibus et. Blandit massa enim nec dui nunc mattis enim ut. Massa placerat duis ultricies lacus sed turpis tincidunt id. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Lectus sit amet est placerat. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Hac habitasse platea dictumst vestibulum rhoncus est. Faucibus purus in massa tempor nec. Turpis massa tincidunt dui ut ornare lectus sit. Nunc faucibus a pellentesque sit amet porttitor. Turpis nunc eget lorem dolor sed. Semper eget duis at tellus at.

  Proin nibh nisl condimentum id venenatis a. Egestas congue quisque egestas diam in arcu cursus. Adipiscing bibendum est ultricies integer quis. Lorem ipsum dolor sit amet consectetur adipiscing. Condimentum lacinia quis vel eros donec ac odio tempor orci. Elit duis tristique sollicitudin nibh sit. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Morbi enim nunc faucibus a. Proin sed libero enim sed faucibus turpis in. Massa sapien faucibus et molestie ac feugiat. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Convallis aenean et tortor at risus viverra adipiscing at. Mauris vitae ultricies leo integer malesuada nunc. Imperdiet sed euismod nisi porta lorem mollis aliquam.

  Magna etiam tempor orci eu lobortis elementum nibh tellus. Convallis tellus id interdum velit laoreet id. Euismod lacinia at quis risus sed vulputate odio ut. Vitae semper quis lectus nulla. Pretium viverra suspendisse potenti nullam ac tortor. Enim praesent elementum facilisis leo vel fringilla. Lectus proin nibh nisl condimentum id. Ultricies lacus sed turpis tincidunt id aliquet risus. Ac placerat vestibulum lectus mauris ultrices eros. Viverra accumsan in nisl nisi scelerisque eu ultrices. Gravida neque convallis a cras semper auctor neque. Aliquam purus sit amet luctus venenatis lectus magna. Sit amet volutpat consequat mauris. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices.
      </p>
    </div>
  )
}

export default TextBody;